language: r

warnings_are_errors: true

apt_packages:
 - libcurl4-openssl-dev
 - libxml2-dev
r_binary_packages:
 - RUnit
 - testthat

# Install the bleeding edge version of a package from github (eg to pick
# up a not-yet-released bugfix)
r_github_packages:
 - rikenbit/meshr_release/meshr

notifications:
  emails:
    - k.t.the-answer@hotmail.co.jp
  on_failure: always